package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataTest2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String i1;

	private java.lang.String i2;

	private java.lang.String i3;

	public DataTest2() {
	}

	public java.lang.String getI1() {
		return this.i1;
	}

	public void setI1(java.lang.String i1) {
		this.i1 = i1;
	}

	public java.lang.String getI2() {
		return this.i2;
	}

	public void setI2(java.lang.String i2) {
		this.i2 = i2;
	}

	public java.lang.String getI3() {
		return this.i3;
	}

	public void setI3(java.lang.String i3) {
		this.i3 = i3;
	}

	public DataTest2(java.lang.String i1, java.lang.String i2,
			java.lang.String i3) {
		this.i1 = i1;
		this.i2 = i2;
		this.i3 = i3;
	}

}