package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataTest9 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String i1;

	public DataTest9() {
	}

	public java.lang.String getI1() {
		return this.i1;
	}

	public void setI1(java.lang.String i1) {
		this.i1 = i1;
	}

	public DataTest9(java.lang.String i1) {
		this.i1 = i1;
	}

}