package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test11 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public test11() {
    }




}